### ISSUE TITLE
Document functions

### ISSUE THREAD

**Issue by annakrystalli** [EMODnet/EMODnetWCS#4]
- [x] #5 
- [x] #11 
- [x] #12 
- [x] Document functions in #2 
- [x] Document functions in #3 
- [x] Document functions in #7 

## Vignettes
- [ ]
