### ISSUE TITLE
Test functions

### ISSUE THREAD

**Issue by annakrystalli** [EMODnet/EMODnetWCS#9]
- [x] #5 
- [x] #10
- [x] Test functions in #2 
- [x] Test functions in #3 
- [x] Test functions in #7
